name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      matrix:
        firefox-version: ['latest']
        node-version: ['20.x', '21.x']
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-firefox@v1

      # libEGL
      - name: Install libEGL dependency
        run: sudo apt-get install -y libegl1

      # Firefox browser.
      - name: Setup Firefox ${{ matrix.firefox-version }}
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox-version }}
      - run: |
          echo Install Firefox browser: ${{ steps.setup-firefox.outputs.firefox-version }}
          ${{ steps.setup-firefox.outputs.firefox-path }} --version

      # Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run WDIO
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test
